---
deployment:
  tasks:
    - export DEPLOYPATH=/home/jywxwido/heartconnect.ruwarehabcentre.com
    
    - echo "Starting deployment"
    
    - /bin/cp -R * $DEPLOYPATH
    
    - cd $DEPLOYPATH
    
    - npm install
    
    - npm run build || true
